name: Build

on:
  workflow_call:
    inputs:
      charms:
        description: List of charms to build
        required: true
        type: string
        default: '[]'

jobs:
  build:
    if: ${{ inputs.charms != '[]' }}
    name: Build charm
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        charm: ${{ fromJson(inputs.charms) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.3
        with:
          channel: 5.21/stable
      - name: Install dependencies
        run: sudo snap install charmcraft --channel 2.x/stable --classic
      - name: Build charm
        run: |
          cd ${{ matrix.charm }}
          charmcraft -v pack
