name: Build

on:
  workflow_call:
    inputs:
        charms:
            description: List of charms to test
            required: true
            type: string
            default: '[]'

jobs:
  build:
    name: Build charm
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        charm: ${{ fromJson(inputs.charms) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo snap install charmcraft --channel 2.x/stable
      - name: Build charm
        run: |
          cd $charm
          charmcraft -v pack
