name: Modified Charms

on:
  workflow_call:
    outputs:
        charms:
            description: List of modified charms as a json string.
            value: ${{ jobs.modifiedcharms.outputs.charms }}

jobs:
  modifiedcharms:
    runs-on: ubuntu-22.04
    outputs:
      charms: ${{ steps.changed-charms.outputs.charms }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files and directories
        id: changed_files
        uses: tj-actions/changed-files@v46
        with:
          dir_names: true
          dir_names_max_depth: 1
          files_ignore: .github/workflows/*.yaml

      - name: set output
        id: changed-charms
        run: |
          modified_dirs=${{ steps.changed_files.outputs.all_changed_files }}
          modified_charms=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${modified_dirs[@]}")
          echo "Modified charms: $modified_charms"
          echo "charms=$modified_charms" >> $GITHUB_OUTPUT
