name: Test

on:
  workflow_call:
    inputs:
        charms:
            description: List of charms to test
            required: true
            type: string
            default: '[]'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        charm: ${{ fromJson(inputs.charms) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: |
          cd $charm
          tox -e pep8

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        charm: ${{ fromJson(inputs.charms) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run tests
        run: |
          cd $charm
          tox -e py3
